server:
  port: 8761                    # 指定该Eureka实例的端口   
  #ssl:
     #client-auth: want
     #key-store: classpath:keystore.jks
     #key-store-password: 123456
     #keyStoreType: JKS
     #key-alias: certificatekey

eureka:
  instance:
    hostname: localhost         # 指定该Eureka实例的主机名
  nonSecurePortEnabled: false
  securePortEnabled: true
  client:
    registerWithEureka: false
    fetchRegistry: false
  serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

  server:
     enableSelfPreservation: false
